saving data in DB and encrypting the password
Yosziad/Electric-store pull request #6
Opened 2020-11-02 08:30 UTC by Yosziad

i also changed the login from get req to post req

2020-11-02 09:48 UTC, beniostr requested changes

2020-11-02 09:48 UTC, beniostr commented on server/controllers/order.js
>  };
const getAllOrders = async (req, res) => {
  let foundOrders;
  try {
    foundOrders = await Order.find().exec();
  } catch (e) {
    logger.error(err);
    return res.status(500).json({
      message: err,
    });
  }
  
  if (!foundOrders) {
    return res.status(404).json({
      message: 'There are no orders to fetch',
    });
  }
  logger.info('Fetching all orders');
  return res.status(200).json({
    message: 'Orders details',
    foundOrders,
  });
};

2020-11-02 09:48 UTC, beniostr commented on server/controllers/order.js
> +      });
use async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/order.js
> +      });
async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/product.js
> +    });
async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/product.js
> +      });
async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/product.js
> +      });
async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/product.js
> +      });
async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/user.js
> +  if ((password).length < 8) {
password.length < 8

2020-11-02 09:48 UTC, beniostr commented on server/controllers/user.js
> +      });
async await

2020-11-02 09:48 UTC, beniostr commented on server/controllers/user.js
>  };
const createUser = (req, res) => {
  const currUser = {
    userName: req.body.userName,
    password: req.body.password,
    firstName: req.body.firstName,
    lastName: req.body.lastName,
    address: req.body.address,
    age: req.body.age,
  };
  logger.info('handling create a user request', currUser);
  try {
    newUserValidation(currUser);
  } catch (err) {
    logger.error(err, user);
    return res.status(400).send('Error: creating a new user failed');
  }
  
  bcrypt.hash(req.body.password, saltRounds, async (error, hash) => {
    const user = new User({...currUser, password: hash});
    try {
      await user.save();
    } catch (err) {
      logger.error(err);
      return res.status(500).json({
        message: err.message,
      });
    }
    logger.info('user created successfully', user);
    return res.send('user created successfully');
  });
};

2020-11-02 09:48 UTC, beniostr commented on server/controllers/user.js
> +      });
async await

2020-11-02 09:49 UTC, beniostr commented
use tokens

router.post('/', controller.createUser); // guest + give token

router.post('/login', controller.loginUser); // guest + give token

router.delete('/:userId', controller.deleteUser); // user

router.post('/', controller.createProduct); // admin token

router.get('/', controller.getProducts); // guest

router.get('/:productId', controller.getProductById); // guest

router.patch('/:productId', controller.updateProduct);// admin

router.delete('/:productId', controller.deleteProduct);// admin

router.get('/', controller.getAllOrders); // admin

router.post('/', controller.createOrder); // user

router.get('/orders/:orderId', controller.getOrder); // user

router.get('/usersOrders/:user', controller.getOrdersByUsername); // user

2020-11-07 14:45 UTC, benios requested changes

2020-11-07 14:45 UTC, benios commented on server/controllers/order.js
> +    return res.status(404).json({
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/order.js
> +  order.save();
you created an order before validating, and you didn't handle it, it is a promise, either use then and catch or use await with try and catch

2020-11-07 14:45 UTC, benios commented on server/controllers/order.js
> +  if (!foundOrder) {
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/order.js
> +  if (!foundOrders) {
log missing

2020-11-07 14:45 UTC, benios commented on server/controllers/order.js
> +  }
I think it is better to create a new middleware for this check

2020-11-07 14:45 UTC, benios commented on server/controllers/product.js
> +  product.save();
then & catch ?
await with try and catch?

2020-11-07 14:45 UTC, benios commented on server/controllers/product.js
> +    return res.status(404).json({
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/product.js
>      return res.status(404).json({
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/product.js
> +  if (!result) {
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/product.js
> +  if (!result) {
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +const saltRounds = 10;
const SALT_ROUNDS = 10;
a standard for using "global" page consts

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +  if (!foundUser) {
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +  return res.status(401).json({
missing log

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +    newUserValidation(currUser);
I think validation be before the existing user check

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +  bcrypt.hash(req.body.password, saltRounds, async (error, hash) => {
change line to use await with try and catch

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +  }
you could have use the middleware I suggested and spare this code

2020-11-07 14:45 UTC, benios commented on server/controllers/user.js
> +  if (!result) {
missing log

2020-11-07 14:45 UTC, benios commented on server/middleware/check-auth.js
> +    return res.status(500).json({
add log

2020-11-07 14:45 UTC, benios commented on server/middleware/check-auth.js
> +    return res.send('Not allowed');
combine to one line

2020-11-07 14:45 UTC, benios commented on server/middleware/check-auth.js
> +    return res.send('Not allowed');
and log

2020-11-07 14:45 UTC, benios commented on server/model/order.js
> +});
check on required fields

2021-01-07 10:04 UTC, merged